# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
  # api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4dec1ef1003136d63f2ea0f063775545ec6bb628959d9eb739b2ee79f4da3d4d5615471069141e07dcf9276b0108ce3aac71d4890d2acda4c370de692d41e1cf

test:
  secret_key_base: fc7de10e4577f9efd7d3b492bf13c23d0e4ab83748e95e906ea4c2810978bc2bc643f2529feb04a9b4cb3a21b01568ed3ff72c0fcfa4c6a1b27a8320ad96e40d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
